import type { CSSProperties } from "react";

export const uiStyles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100%",
    color: "#0f172a",
  },

  headerRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "16px",
    marginBottom: "20px",
    flexWrap: "wrap",
  },
  title: {
    margin: 0,
    fontSize: "28px",
    fontWeight: 700,
    color: "#0f172a",
  },
  subtitle: {
    margin: "8px 0 0 0",
    fontSize: "14px",
    color: "#64748b",
  },

  primaryActionButton: {
    border: "none",
    borderRadius: "14px",
    background: "#0f172a",
    color: "#fff",
    padding: "12px 18px",
    fontSize: "14px",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 10px 25px rgba(15,23,42,0.14)",
    whiteSpace: "nowrap" as const,
    minHeight: "44px",
  },
  secondaryActionButton: {
    border: "1px solid #cbd5e1",
    background: "#fff",
    color: "#334155",
    borderRadius: "14px",
    padding: "12px 18px",
    fontSize: "14px",
    fontWeight: 700,
    cursor: "pointer",
    minHeight: "44px",
  },
  primaryActionButtonDisabled: {
    opacity: 0.65,
    cursor: "not-allowed",
    boxShadow: "none",
  },

  summaryRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
    gap: "16px",
    marginBottom: "20px",
  },
  summaryCard: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: "20px",
    padding: "18px",
    boxShadow: "0 10px 30px rgba(15,23,42,0.05)",
  },
  summaryLabel: {
    margin: 0,
    fontSize: "12px",
    fontWeight: 600,
    color: "#64748b",
    textTransform: "uppercase" as const,
    letterSpacing: "0.04em",
  },
  summaryValue: {
    margin: "8px 0 0 0",
    fontSize: "26px",
    fontWeight: 800,
    color: "#0f172a",
  },

  panel: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: "20px",
    padding: "16px",
    boxShadow: "0 10px 30px rgba(15,23,42,0.05)",
    overflow: "hidden",
  },

  alertError: {
    marginBottom: "16px",
    borderRadius: "14px",
    border: "1px solid #fecaca",
    background: "#fef2f2",
    color: "#b91c1c",
    padding: "12px 14px",
    fontSize: "14px",
  },

  skeletonWrap: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  skeletonBlock: {
    height: "18px",
    borderRadius: "999px",
    background:
      "linear-gradient(90deg, rgba(226,232,240,0.9) 25%, rgba(241,245,249,1) 50%, rgba(226,232,240,0.9) 75%)",
    backgroundSize: "200% 100%",
  },

  emptyState: {
    textAlign: "center" as const,
    padding: "48px 20px",
  },
  emptyIcon: {
    fontSize: "44px",
    marginBottom: "14px",
  },
  emptyTitle: {
    margin: 0,
    fontSize: "22px",
    fontWeight: 700,
    color: "#0f172a",
  },
  emptyText: {
    margin: "10px auto 0 auto",
    fontSize: "14px",
    color: "#64748b",
    maxWidth: "420px",
  },
  emptyButton: {
    marginTop: "18px",
    border: "none",
    borderRadius: "14px",
    background: "#0f172a",
    color: "#fff",
    padding: "12px 18px",
    fontSize: "14px",
    fontWeight: 700,
    cursor: "pointer",
    minHeight: "44px",
  },

  // Table: horizontal scroll wrapper — tables scroll on mobile rather than breaking
  tableWrap: {
    display: "flex",
    flexDirection: "column",
    overflowX: "auto",
    WebkitOverflowScrolling: "touch",
  } as CSSProperties,
  tableHeader: {
    display: "grid",
    gap: "16px",
    padding: "14px 12px",
    borderBottom: "1px solid #e5e7eb",
    color: "#475569",
    fontSize: "13px",
    fontWeight: 700,
    textTransform: "uppercase" as const,
    letterSpacing: "0.04em",
    minWidth: "600px",
  },
  tableRow: {
    display: "grid",
    gap: "16px",
    alignItems: "start",
    padding: "16px 12px",
    borderBottom: "1px solid #f1f5f9",
    position: "relative" as const,
    minWidth: "600px",
  },
  rowTitle: {
    fontSize: "14px",
    fontWeight: 700,
    color: "#0f172a",
  },
  rowSub: {
    marginTop: "4px",
    fontSize: "12px",
    color: "#64748b",
  },
  cellMuted: {
    fontSize: "13px",
    color: "#475569",
    wordBreak: "break-word" as const,
    paddingTop: "2px",
  },

  statusBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "999px",
    padding: "4px 10px",
    fontSize: "12px",
    fontWeight: 700,
    border: "1px solid transparent",
    whiteSpace: "nowrap" as const,
  },
  statusBlue: {
    background: "#eff6ff",
    color: "#1d4ed8",
    borderColor: "#bfdbfe",
  },
  statusGreen: {
    background: "#ecfdf5",
    color: "#047857",
    borderColor: "#a7f3d0",
  },
  statusYellow: {
    background: "#fefce8",
    color: "#a16207",
    borderColor: "#fde68a",
  },
  statusRed: {
    background: "#fef2f2",
    color: "#b91c1c",
    borderColor: "#fecaca",
  },
  statusGray: {
    background: "#f8fafc",
    color: "#475569",
    borderColor: "#cbd5e1",
  },

  actionCell: {
    position: "relative" as const,
    display: "flex",
    justifyContent: "flex-end",
  },
  menuButton: {
    border: "1px solid #e2e8f0",
    background: "#fff",
    color: "#334155",
    borderRadius: "12px",
    width: "36px",
    height: "36px",
    cursor: "pointer",
    fontSize: "18px",
    lineHeight: 1,
  },
  menuPopover: {
    position: "absolute" as const,
    top: "44px",
    right: 0,
    minWidth: "140px",
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: "14px",
    boxShadow: "0 20px 40px rgba(15,23,42,0.12)",
    overflow: "hidden",
    zIndex: 20,
  },
  menuItem: {
    width: "100%",
    border: "none",
    background: "#fff",
    padding: "12px 14px",
    fontSize: "14px",
    textAlign: "left" as const,
    cursor: "pointer",
    color: "#0f172a",
  },
  menuItemDanger: {
    color: "#b91c1c",
    borderTop: "1px solid #f1f5f9",
  },

  // Modal: full-screen on mobile
  modalBackdrop: {
    position: "fixed" as const,
    inset: 0,
    background: "rgba(15, 23, 42, 0.52)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "16px",
    zIndex: 50,
  },
  modalCard: {
    width: "100%",
    maxWidth: "720px",
    background: "#fff",
    borderRadius: "20px",
    boxShadow: "0 30px 80px rgba(15,23,42,0.22)",
    padding: "24px",
    maxHeight: "90vh",
    overflowY: "auto" as const,
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "16px",
    marginBottom: "20px",
  },
  modalTitle: {
    margin: 0,
    fontSize: "22px",
    fontWeight: 800,
    color: "#0f172a",
  },
  modalSubtitle: {
    margin: "8px 0 0 0",
    fontSize: "14px",
    color: "#64748b",
  },
  closeBtn: {
    border: "1px solid #e2e8f0",
    background: "#fff",
    color: "#334155",
    borderRadius: "12px",
    width: "38px",
    height: "38px",
    cursor: "pointer",
    fontSize: "16px",
    flexShrink: 0,
  },

  form: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "16px",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  label: {
    fontSize: "14px",
    fontWeight: 700,
    color: "#334155",
  },
  input: {
    width: "100%",
    border: "1px solid #cbd5e1",
    borderRadius: "14px",
    padding: "12px 14px",
    // 16px prevents iOS auto-zoom on focus
    fontSize: "16px",
    color: "#0f172a",
    outline: "none",
    background: "#fff",
    boxSizing: "border-box" as const,
  },
  textarea: {
    width: "100%",
    border: "1px solid #cbd5e1",
    borderRadius: "14px",
    padding: "12px 14px",
    fontSize: "16px",
    color: "#0f172a",
    outline: "none",
    resize: "vertical" as const,
    minHeight: "110px",
    background: "#fff",
    boxSizing: "border-box" as const,
    fontFamily: "inherit",
  },

  modalActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "12px",
    marginTop: "8px",
    flexWrap: "wrap" as const,
  },

  toast: {
    position: "fixed" as const,
    top: "16px",
    right: "16px",
    left: "16px",
    zIndex: 80,
    borderRadius: "14px",
    padding: "14px 16px",
    color: "#fff",
    fontSize: "14px",
    fontWeight: 700,
    boxShadow: "0 20px 40px rgba(15,23,42,0.18)",
  },
  toastSuccess: {
    background: "#16a34a",
  },
  toastError: {
    background: "#dc2626",
  },
};

export const candidatePageStyles: Record<string, CSSProperties> = {
  notesText: {
    marginTop: "8px",
    fontSize: "13px",
    color: "#475569",
    lineHeight: 1.45,
  },
  inviteBox: {
    padding: "16px",
    borderRadius: "16px",
    border: "1px solid #bfdbfe",
    background: "#eff6ff",
  },
  inviteTitle: {
    margin: 0,
    fontSize: "14px",
    fontWeight: 800,
    color: "#1e3a8a",
  },
  inviteText: {
    margin: "6px 0 0 0",
    fontSize: "13px",
    color: "#1d4ed8",
  },
  inviteLinkRow: {
    display: "flex",
    gap: "10px",
    marginTop: "12px",
    alignItems: "stretch",
    flexWrap: "wrap",
  },
  inviteInput: {
    flex: 1,
    minWidth: "160px",
    border: "1px solid #cbd5e1",
    borderRadius: "12px",
    padding: "12px 14px",
    fontSize: "13px",
    color: "#0f172a",
    background: "#fff",
    boxSizing: "border-box" as const,
  },
  copyButton: {
    border: "none",
    borderRadius: "12px",
    background: "#2563eb",
    color: "#fff",
    padding: "0 16px",
    fontSize: "13px",
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
    minHeight: "44px",
  },
  openInviteLink: {
    display: "inline-block",
    marginTop: "10px",
    fontSize: "13px",
    fontWeight: 700,
    color: "#1d4ed8",
    textDecoration: "none",
  },
};
